### ISSUE TITLE
Can't read the page on mobile, even in desktop mode 

### ISSUE THREAD

**Issue by Mongoose69** [TomMalufe/Prompt-Helper#1]

**Comment by TomMalufe** [comment]
Yeah, I realized this myself just yesterday.  I'm planning to revamp the app this weekend to work better on mobile, as well as give the user options to add new tags or remove unwanted tags.

**Comment by TomMalufe** [comment]
Should work better on mobile now.  In fact, I just changed the whole layout to be a "mobile first" design.
